spring:
  datasource:
    url: jdbc:h2:file:/data/crud-service
    username: sa
    password: s
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
     ddl-auto: create
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
   console:
    enabled: true